### PR TITLE
web scrapper

### PR DESCRIPTION
**Pull request by lovendatj**
started collecting urls from robots.txt of a given website. I started adding json files per website and collecting some base data that way. There is probably a library for half the stuff I wrote. i found newspaper library but not much implementation

### CODE REVIEW

**Comment by zachwildd** [comment]
Hey, so I set up scraping with scrapy -- I found a set of articles that also have summaries to use -- and it's great because it does so much automatically. You just set on parameter in the config and it follows robots.txt for any site, also I added my email to the user-agent so if scraping causes any issues they have my contact info.

**Comment by zachwildd** [comment]
Also, this commit has those .pyc files -- those shouldn't get added to source control.

**Comment by lovendatj** [comment]
Alright. Do you have any articles about the actual scraping process? Curious to how they get around apis, or if they use emulators.

**Comment by zachwildd** [comment]
If anything you'd want to use their API if it's available. I haven't heard of anyone using an emulator before, but you can read about https://scrapy.org/. They pretty much do the exact same thing you do when you visit a website. The interesting part is cleaning the HTML files.

**Pull request closed without merging**
